# En-Fr
cd run/en_fr
python test_MMTransE_lan_mapping_15k_fk.py
python test_MMTransE_lan_mapping_120k_fk.py
cd ../en_de
# En-De
python test_MMTransE_lan_mapping_15k_fk.py
python test_MMTransE_lan_mapping_120k_fk.py
cd ../..
