# En-Fr
cd run/en_fr
python train_MMtransE_15k.py
python train_MMtransE_120k.py
python train_MMtransE_cn.py
# En-De
cd ../en_de
python train_MMtransE_15k.py
python train_MMtransE_120k.py
python train_MMtransE_cn.py
cd ../..
